### ISSUE TITLE
Resulting firmware version: 99.55

### ISSUE THREAD

**Issue by kgslovak** [bitcraze/crazyradio-firmware#49]
I followed the readme instructions for flashing a crazyradio PA on Ubuntu (built the firmware from the repo files). I then ran the command provided in the wiki to check the firmware version:

$ lsusb -d 1915:7777 -v | grep bcdDevice
  bcdDevice           99.55

Is it supposed to be 99.55? That seems odd considering the latest release binary for crazyradio pa is:

cradio-pa-0.53.bin

**Comment by ataffanel** [comment]
If you build from master this is correct, this is a trick I have been using for development: 99.something is big enough to pass all version tests in the drivers and it looks weird enough so that it makes it obvious that this is not a released version.

If you build the tagged version in git you will get version 0.53.
